<?php
/**
 * Created by PhpStorm.
 * User: chl
 * Date: 30.03.15
 * Time: 09:33
 */

namespace RA\SilexRestApi\Connector\Oxid;


use RA\SilexRestApi\Filter\Constraint\Like;
use RA\SilexRestApi\Filter\Constraint\LogicalOr;
use RA\SilexRestApi\Filter\Filter;
use Symfony\Component\HttpFoundation\Request;

class DefaultCategoryFilter extends Filter {



    public function setRequest(Request $request)
    {
        parent::setRequest($request); // TODO: Change the autogenerated stub

        $search = $request->get('q');
        if ($search != '')
        {
            $constraint = new LogicalOr(
                new Like('OXTITLE', '%' . $search . '%'),
                new Like('OXDESC', '%' . $search . '%')
            );

            $this->setRootConstraint($constraint);
        }

    }


}